/**
 * AgentPlanSchema - Output schema for PlanBuilder
 *
 * Defines the structure of task plans generated by the plan builder.
 * Includes dependency handling and failure strategies.
 *
 * NOTE: Azure OpenAI strict structured output requires ALL properties in 'required'.
 * Do NOT use .default() or .optional() — they remove the property from 'required'
 * in the generated JSON schema, causing 400 errors.
 * Use .describe() to hint at recommended values instead.
 */

import { z } from "zod";

/**
 * Schema for task context
 */
const TaskContextSchema = z.object({
  files: z.array(z.string()).describe("Relevant file paths (empty array if none)"),
  artifacts: z.array(z.string()).describe("Related artifact IDs (empty array if none)"),
  notes: z.string().describe("Additional notes (empty string if none)"),
  relatedTasks: z.array(z.string()).describe("Related task IDs (empty array if none)"),
});

/**
 * Schema for a single task
 */
export const TaskItemSchema = z.object({
  id: z.string().describe("Unique task identifier"),
  title: z.string().describe("Short task title"),
  description: z.string().describe("Detailed task description"),
  assignedRole: z.string().describe("Role responsible for this task"),
  priority: z
    .number()
    .min(1)
    .max(5)
    .describe("Priority level (1=highest, 5=lowest, recommend 3)"),

  // Complexity estimation
  complexity: z
    .enum(["low", "medium", "high"])
    .describe(
      "Estimated effort: low=quick fix, medium=normal task, high=complex work",
    ),

  // Dependencies
  dependencies: z
    .array(z.string())
    .describe("Task IDs that must complete before this one (empty array if none)"),

  // Failure handling
  onDependencyFail: z
    .enum(["skip", "fail", "replan"])
    .describe(
      "What to do if a dependency fails: skip this task, fail this task, or trigger re-planning",
    ),

  // Expected output
  expectedOutput: z
    .string()
    .describe("Description of expected output (empty string if unknown)"),

  // Context
  context: TaskContextSchema.describe("Additional context for the task"),
});

/**
 * Schema for a phase (group of related tasks)
 */
const PhaseSchema = z.object({
  id: z.string().describe("Phase identifier"),
  name: z.string().describe("Phase name"),
  description: z.string().describe("Phase description (empty string if none)"),
  tasks: z.array(z.string()).describe("Task IDs in this phase"),
  order: z.number().describe("Execution order (lower = earlier)"),
});

/**
 * Schema for the complete plan output
 */
export const AgentPlanSchema = z.object({
  planId: z.string().describe("Unique plan identifier"),
  goal: z.string().describe("The overall goal this plan achieves"),
  tasks: z.array(TaskItemSchema).describe("List of tasks to execute"),
  phases: z
    .array(PhaseSchema)
    .describe("Grouping of tasks into phases (empty array if not phased)"),
  estimatedDuration: z
    .string()
    .describe("Estimated time to complete all tasks (empty string if unknown)"),
  successCriteria: z
    .array(z.string())
    .describe("Criteria to determine if plan succeeded (empty array if none)"),
});

export type TaskItem = z.infer<typeof TaskItemSchema>;
export type AgentPlanOutput = z.infer<typeof AgentPlanSchema>;
