/**
 * AgentConfigSchema - Output schema for ConfigBuilder
 *
 * Defines the structure of agent configurations generated by the config builder.
 *
 * NOTE: Azure OpenAI strict structured output requires ALL properties in 'required'.
 * Do NOT use .default() or .optional() — they remove the property from 'required'
 * in the generated JSON schema, causing 400 errors.
 * Use .describe() to hint at recommended values instead.
 */

import { z } from "zod";

/**
 * Schema for model configuration
 */
const ModelConfigSchema = z.object({
  provider: z
    .enum(["anthropic", "openai", "azure-openai"])
    .describe("LLM provider (use 'azure-openai' if unsure)"),
  model: z.string().describe("Model name (empty string if using deployment instead)"),
  deployment: z.string().describe("Azure deployment name (empty string if not Azure)"),
  temperature: z.number().min(0).max(2).describe("Temperature (0.0 to 2.0, recommend 0.7)"),
  maxTokens: z.number().describe("Max tokens (e.g. 4096)"),
});

/**
 * Schema for tool configuration
 * NOTE: Azure OpenAI doesn't support z.record() with propertyNames, so config is a JSON string
 */
const ToolConfigSchema = z.object({
  name: z.string().describe("Tool name"),
  type: z.enum(["builtin", "mcp", "custom"]).describe("Tool type (use 'builtin' if unsure)"),
  configJson: z
    .string()
    .describe("Tool configuration as JSON string (use '{}' if none)"),
});

/**
 * Schema for memory configuration
 */
const MemoryConfigSchema = z.object({
  shortTerm: z.boolean().describe("Enable short-term memory (recommend true)"),
  checkpoint: z.boolean().describe("Enable checkpointing (recommend true)"),
  longTerm: z.boolean().describe("Enable long-term memory (recommend false)"),
});

/**
 * Schema for a single agent configuration
 */
export const AgentConfigItemSchema = z.object({
  role: z.string().describe("The role this config is for"),
  name: z.string().describe("Human-readable name for the agent"),
  description: z.string().describe("Description of the agent (empty string if none)"),
  systemPrompt: z.string().describe("The system prompt for the agent"),
  model: ModelConfigSchema.describe("Model configuration"),
  tools: z
    .array(ToolConfigSchema)
    .describe("Tools the agent can use (empty array if none)"),
  memory: MemoryConfigSchema.describe("Memory configuration"),
});

/**
 * Schema for shared settings
 */
const SharedSettingsSchema = z.object({
  streaming: z.boolean().describe("Enable streaming (recommend true)"),
  timeout: z.number().describe("Timeout in ms (recommend 30000)"),
  retries: z.number().describe("Number of retries (recommend 3)"),
});

/**
 * Schema for the complete config output
 */
export const AgentConfigSchema = z.object({
  configs: z
    .array(AgentConfigItemSchema)
    .describe("List of agent configurations"),
  sharedSettings: SharedSettingsSchema.describe("Settings shared across all agents"),
});

export type AgentConfigItem = z.infer<typeof AgentConfigItemSchema>;
export type AgentConfigOutput = z.infer<typeof AgentConfigSchema>;
