/**
 * PgGoalService — PostgreSQL implementation of IGoalService.
 *
 * Design:
 *   - PK (`id`) is a DB-generated UUID — stable for FKs, never exposed to business logic
 *   - Business identifier (`goal_id`) is a unique-indexed column — used for all lookups
 *   - Service layer maps between Goal interface (uses goalId) and PG columns
 */

import { eq, desc } from "drizzle-orm";
import type { IGoalService } from "../contracts/index.js";
import type { Goal } from "../types/index.js";
import { getDb } from "../../db/connection.js";
import { goals, agentTeams } from "../../db/schema.js";

export class PgGoalService implements IGoalService {
  private get db() {
    return getDb();
  }

  async addGoal(goal: Omit<Goal, "id" | "createdAt" | "updatedAt">): Promise<Goal> {
    const now = new Date();

    // Resolve team UUID from business teamId
    const teamUuid = await this.resolveTeamUuid(goal.teamId);

    const [row] = await this.db
      .insert(goals)
      .values({
        // id: auto-generated by DB (gen_random_uuid())
        goalId: goal.goalId || crypto.randomUUID(),
        agentTeamId: teamUuid,
        createdBy: goal.userId,
        title: goal.goal,
        status: this.mapStatusToEnum(goal.status),
        repoUrl: goal.repoUrl ?? null,
        repoBranch: goal.repoBranch ?? null,
        planId: goal.planId ?? null,
        result: goal.result ?? null,
        createdAt: now,
        updatedAt: now,
      })
      .returning();

    return this.toGoal(row, goal.teamId);
  }

  async getGoals(teamId: string, options?: { limit?: number }): Promise<Goal[]> {
    const limit = Math.min(options?.limit ?? 20, 100);

    const rows = await this.db
      .select({
        id: goals.id,
        goalId: goals.goalId,
        agentTeamId: goals.agentTeamId,
        createdBy: goals.createdBy,
        title: goals.title,
        status: goals.status,
        repoUrl: goals.repoUrl,
        repoBranch: goals.repoBranch,
        planId: goals.planId,
        approvedBy: goals.approvedBy,
        result: goals.result,
        createdAt: goals.createdAt,
        updatedAt: goals.updatedAt,
        teamId: agentTeams.teamId,
      })
      .from(goals)
      .innerJoin(agentTeams, eq(goals.agentTeamId, agentTeams.id))
      .where(eq(agentTeams.teamId, teamId))
      .orderBy(desc(goals.createdAt))
      .limit(limit);

    return rows.map((r) => ({
      id: r.goalId,
      teamId: r.teamId,
      userId: r.createdBy,
      goal: r.title,
      goalId: r.goalId,
      status: r.status as Goal["status"],
      planId: r.planId ?? undefined,
      result: r.result ?? undefined,
      repoUrl: r.repoUrl ?? undefined,
      repoBranch: r.repoBranch ?? undefined,
      createdAt: r.createdAt?.toISOString() ?? new Date().toISOString(),
      updatedAt: r.updatedAt?.toISOString() ?? new Date().toISOString(),
    }));
  }

  async updateGoal(goalId: string, updates: Partial<Goal>): Promise<Goal | null> {
    const setValues: Record<string, unknown> = { updatedAt: new Date() };

    if (updates.status) setValues.status = this.mapStatusToEnum(updates.status);
    if (updates.result !== undefined) setValues.result = updates.result;
    if (updates.planId !== undefined) setValues.planId = updates.planId;
    if (updates.repoUrl !== undefined) setValues.repoUrl = updates.repoUrl;
    if (updates.repoBranch !== undefined) setValues.repoBranch = updates.repoBranch;

    // Lookup by business goal_id (unique indexed)
    const rows = await this.db
      .update(goals)
      .set(setValues)
      .where(eq(goals.goalId, goalId))
      .returning();

    return rows.length > 0 ? this.toGoal(rows[0]) : null;
  }

  /** Resolve business teamId (SHA-256 hash) to DB UUID */
  private async resolveTeamUuid(teamId: string): Promise<string> {
    const rows = await this.db
      .select({ id: agentTeams.id })
      .from(agentTeams)
      .where(eq(agentTeams.teamId, teamId))
      .limit(1);

    if (rows.length === 0) {
      throw new Error(
        `Agent team not found in PostgreSQL for teamId: ${teamId}. ` +
        `The team must be installed (POST /api/v2/teams) before goals can be created. ` +
        `In dev, run 'bun run seed:teams' to register plugin teams.`
      );
    }
    return rows[0].id;
  }

  private mapStatusToEnum(status?: string): "pending" | "planning" | "researching" | "awaiting_approval" | "executing" | "completed" | "failed" {
    const valid = ["pending", "planning", "researching", "awaiting_approval", "executing", "completed", "failed"] as const;
    if (status && valid.includes(status as any)) return status as any;
    return "pending";
  }

  private toGoal(row: typeof goals.$inferSelect, teamId?: string): Goal {
    return {
      id: row.goalId, // Business code sees goalId as the "id"
      teamId: teamId ?? "",
      userId: row.createdBy,
      goal: row.title,
      goalId: row.goalId,
      status: row.status as Goal["status"],
      planId: row.planId ?? undefined,
      result: row.result ?? undefined,
      repoUrl: row.repoUrl ?? undefined,
      repoBranch: row.repoBranch ?? undefined,
      createdAt: row.createdAt?.toISOString() ?? new Date().toISOString(),
      updatedAt: row.updatedAt?.toISOString() ?? new Date().toISOString(),
    };
  }
}
