/**
 * PgTaskService — PostgreSQL implementation of ITaskPersistence.
 *
 * Design:
 *   - PK (`id`) is a DB-generated UUID
 *   - Business task identifier (`task_id`, e.g., "task-1") is unique within a goal
 *   - Compound unique index: (goal_id, task_id) — matches old Mongo {teamId, goalId, taskId}
 *   - Lookups use business task_id + goal UUID, never the PK directly
 */

import { eq, and, ne } from "drizzle-orm";
import type { ITaskPersistence, TaskData } from "@ping/agent-manager/src/orchestrator/contracts/index.js";
import { getDb } from "../../db/connection.js";
import { tasks, goals } from "../../db/schema.js";

export class PgTaskService implements ITaskPersistence {
  private get db() {
    return getDb();
  }

  async saveTasks(goalId: string, teamId: string, taskDataArr: TaskData[]): Promise<void> {
    if (taskDataArr.length === 0) return;

    const now = new Date();

    // Resolve goal business ID to UUID (must exist for writes)
    const goalUuid = await this.requireGoalUuid(goalId);

    // Individual upserts — each row gets its own values on conflict
    for (const t of taskDataArr) {
      await this.db.insert(tasks).values({
        // id: auto-generated by DB (gen_random_uuid())
        taskId: t.taskId,
        goalId: goalUuid,
        title: t.title ?? null,
        description: t.description,
        status: this.mapStatus(t.status),
        assignedRole: t.assignedRole,
        priority: t.priority ?? 3,
        planId: t.planId ?? null,
        output: t.output ?? null,
        dependencies: t.dependencies ?? null,
        createdAt: now,
        updatedAt: now,
      }).onConflictDoUpdate({
        target: [tasks.goalId, tasks.taskId],
        set: {
          title: t.title ?? null,
          description: t.description,
          status: this.mapStatus(t.status),
          assignedRole: t.assignedRole,
          priority: t.priority ?? 3,
          planId: t.planId ?? null,
          dependencies: t.dependencies ?? null,
          updatedAt: now,
        },
      });
    }
  }

  async updateTaskStatus(taskId: string, goalId: string, status: string, output?: unknown): Promise<void> {
    const goalUuid = await this.requireGoalUuid(goalId);

    const setValues: Record<string, unknown> = {
      status: this.mapStatus(status),
      updatedAt: new Date(),
    };
    if (output !== undefined) setValues.output = output;

    await this.db
      .update(tasks)
      .set(setValues)
      .where(and(eq(tasks.taskId, taskId), eq(tasks.goalId, goalUuid)));
  }

  async getTasksByGoal(goalId: string): Promise<TaskData[]> {
    const goalUuid = await this.resolveGoalUuid(goalId);
    if (!goalUuid) return []; // Goal doesn't exist in PG — return empty

    const rows = await this.db
      .select()
      .from(tasks)
      .where(eq(tasks.goalId, goalUuid));

    return rows.map((r) => this.toTaskData(r, goalId));
  }

  async getTasksByTeam(teamId: string): Promise<TaskData[]> {
    const { agentTeams } = await import("../../db/schema.js");

    const rows = await this.db
      .select({
        id: tasks.id,
        taskId: tasks.taskId,
        goalId: tasks.goalId,
        title: tasks.title,
        description: tasks.description,
        status: tasks.status,
        assignedRole: tasks.assignedRole,
        priority: tasks.priority,
        planId: tasks.planId,
        output: tasks.output,
        dependencies: tasks.dependencies,
        createdAt: tasks.createdAt,
        updatedAt: tasks.updatedAt,
        businessGoalId: goals.goalId,
        businessTeamId: agentTeams.teamId,
      })
      .from(tasks)
      .innerJoin(goals, eq(tasks.goalId, goals.id))
      .innerJoin(agentTeams, eq(goals.agentTeamId, agentTeams.id))
      .where(eq(agentTeams.teamId, teamId));

    return rows.map((r) => ({
      taskId: r.taskId,
      goalId: r.businessGoalId,
      teamId: r.businessTeamId,
      title: r.title ?? undefined,
      description: r.description,
      status: r.status,
      assignedRole: r.assignedRole,
      priority: r.priority ?? undefined,
      output: r.output ?? undefined,
      planId: r.planId ?? undefined,
      dependencies: r.dependencies ?? undefined,
      createdAt: r.createdAt?.toISOString(),
      updatedAt: r.updatedAt?.toISOString(),
    }));
  }

  async clearTasksByGoal(goalId: string): Promise<void> {
    const goalUuid = await this.resolveGoalUuid(goalId);
    if (!goalUuid) return; // Goal doesn't exist — nothing to clear
    await this.db.delete(tasks).where(eq(tasks.goalId, goalUuid));
  }

  async clearStaleTasks(goalId: string, currentPlanId: string): Promise<void> {
    const goalUuid = await this.resolveGoalUuid(goalId);
    if (!goalUuid) return; // Goal doesn't exist — nothing to clear
    await this.db
      .delete(tasks)
      .where(and(eq(tasks.goalId, goalUuid), ne(tasks.planId, currentPlanId)));
  }

  /** Resolve business goalId to DB UUID. Returns null if not found (read-safe). */
  private async resolveGoalUuid(goalId: string): Promise<string | null> {
    const rows = await this.db
      .select({ id: goals.id })
      .from(goals)
      .where(eq(goals.goalId, goalId))
      .limit(1);

    return rows.length > 0 ? rows[0].id : null;
  }

  /** Resolve business goalId to DB UUID. Throws if not found (write operations). */
  private async requireGoalUuid(goalId: string): Promise<string> {
    const uuid = await this.resolveGoalUuid(goalId);
    if (!uuid) {
      throw new Error(`Goal not found for goalId: ${goalId}. Ensure the goal exists in PostgreSQL before persisting tasks.`);
    }
    return uuid;
  }

  private mapStatus(status: string): "ready" | "pending" | "in_progress" | "completed" | "failed" | "discarded" {
    const valid = ["ready", "pending", "in_progress", "completed", "failed", "discarded"] as const;
    if (valid.includes(status as any)) return status as any;
    return "pending";
  }

  private toTaskData(row: typeof tasks.$inferSelect, businessGoalId?: string): TaskData {
    return {
      taskId: row.taskId,
      goalId: businessGoalId ?? "",
      teamId: "", // Caller knows context — tasks don't store teamId
      title: row.title ?? undefined,
      description: row.description,
      status: row.status,
      assignedRole: row.assignedRole,
      priority: row.priority ?? undefined,
      output: row.output ?? undefined,
      planId: row.planId ?? undefined,
      dependencies: row.dependencies ?? undefined,
      createdAt: row.createdAt?.toISOString(),
      updatedAt: row.updatedAt?.toISOString(),
    };
  }
}
